### ISSUE TITLE
عبارت «تجربه کاری» در صفحه اول

### ISSUE THREAD

**Issue by saeedesmaili** [jobguywork/website#35]
تو قسمت «شرکت‌های برتر» تو هوم‌پیج، زیر اسم شرکت مجموع تجربه‌های کاری و تجربه‌های مصاحبه درج‌شده برای اون شرکت با تایتل «تجربه‌های کاری» اومده. مثلا:

![image](https://user-images.githubusercontent.com/13351748/119792554-06773600-beeb-11eb-82ea-f75d40858c19.png)

به نظر میاد که کافه‌بازار ۱۶ تجربه کاری براش درج شده،‌در حالی که توی صفحه کافه‌بازار، ۵ تجربه کاری و ۱۱ تجربه مصاحبه درج شده:

![image](https://user-images.githubusercontent.com/13351748/119792695-2575c800-beeb-11eb-8d96-a10001f9fd3f.png)

به نظرم یا باید اون عدد صفحه اول عوض بشه و فقط شامل تجربه‌های کاری بشه، یا عبارتی که کنارش نوشته شده عوض بشه و مشخص باشه که مجموع تجربه‌های کاری و مصاحبه است.

و یه نکته دیگه (که شاید میتونه یه ایشوی مجزا باشه): تو همون بخش شرکت‌های برتر هوم‌پیج، بازه حقوق بعضی شرکت‌ها صفر تا یه عددی هست. این به نظر میاد که باگ باشه و شاید تجربه‌های کاری که حقوق درج نکردن رو صفر در نظر میگیره.

**Comment by pamenary** [comment]
سعید جان درست میگی، الان تغییرش میدم به «تجربه» که مثل صفحه پروفایل یکی بشه 

![image](https://user-images.githubusercontent.com/5821738/119823040-9c21be00-bf09-11eb-912c-8467f028251f.png)

**Comment by pamenary** [comment]
بعد از مرج شدن با master این شکلی میشه

![image](https://user-images.githubusercontent.com/5821738/119824398-1c94ee80-bf0b-11eb-8b9f-74978363aa03.png)
